//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: entity.proto
//
//package osc.innovator.arbitrarygen.demo;
//
//public final class QQUserProtos {
//	private QQUserProtos() {
//	}
//
//	public static void registerAllExtensions(
//			com.google.protobuf.ExtensionRegistry registry) {
//	}
//
//	public interface QQUserOrBuilder extends
//			com.google.protobuf.MessageOrBuilder {
//
//		// required int32 uin = 1 [default = 10000];
//		/**
//		 * <code>required int32 uin = 1 [default = 10000];</code>
//		 */
//		boolean hasUin();
//
//		/**
//		 * <code>required int32 uin = 1 [default = 10000];</code>
//		 */
//		int getUin();
//
//		// required string nick = 2 [default = "n"];
//		/**
//		 * <code>required string nick = 2 [default = "n"];</code>
//		 */
//		boolean hasNick();
//
//		/**
//		 * <code>required string nick = 2 [default = "n"];</code>
//		 */
//		java.lang.String getNick();
//
//		/**
//		 * <code>required string nick = 2 [default = "n"];</code>
//		 */
//		com.google.protobuf.ByteString getNickBytes();
//
//		// required int32 age = 3 [default = 20];
//		/**
//		 * <code>required int32 age = 3 [default = 20];</code>
//		 */
//		boolean hasAge();
//
//		/**
//		 * <code>required int32 age = 3 [default = 20];</code>
//		 */
//		int getAge();
//
//		// required int32 faceId = 4 [default = 0];
//		/**
//		 * <code>required int32 faceId = 4 [default = 0];</code>
//		 */
//		boolean hasFaceId();
//
//		/**
//		 * <code>required int32 faceId = 4 [default = 0];</code>
//		 */
//		int getFaceId();
//	}
//
//	/**
//	 * Protobuf type {@code QQUser}
//	 */
//	public static final class QQUser extends
//			com.google.protobuf.GeneratedMessage implements QQUserOrBuilder {
//		// Use QQUser.newBuilder() to construct.
//		private QQUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
//			super(builder);
//			this.unknownFields = builder.getUnknownFields();
//		}
//
//		private QQUser(boolean noInit) {
//			this.unknownFields = com.google.protobuf.UnknownFieldSet
//					.getDefaultInstance();
//		}
//
//		private static final QQUser defaultInstance;
//
//		public static QQUser getDefaultInstance() {
//			return defaultInstance;
//		}
//
//		public QQUser getDefaultInstanceForType() {
//			return defaultInstance;
//		}
//
//		private final com.google.protobuf.UnknownFieldSet unknownFields;
//
//		@java.lang.Override
//		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
//			return this.unknownFields;
//		}
//
//		private QQUser(com.google.protobuf.CodedInputStream input,
//				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//				throws com.google.protobuf.InvalidProtocolBufferException {
//			initFields();
//			int mutable_bitField0_ = 0;
//			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
//					.newBuilder();
//			try {
//				boolean done = false;
//				while (!done) {
//					int tag = input.readTag();
//					switch (tag) {
//					case 0: {
//						done = true;
//						break;
//					}
//					case 8: {
//						bitField0_ |= 0x00000001;
//						uin_ = input.readInt32();
//						break;
//					}
//					case 18: {
//						bitField0_ |= 0x00000002;
//						nick_ = input.readBytes();
//						break;
//					}
//					case 24: {
//						bitField0_ |= 0x00000004;
//						age_ = input.readInt32();
//						break;
//					}
//					case 32: {
//						bitField0_ |= 0x00000008;
//						faceId_ = input.readInt32();
//						break;
//					}
//					default: {
//						if (!parseUnknownField(input, unknownFields,
//								extensionRegistry, tag)) {
//							done = true;
//						}
//						break;
//					}
//					}
//				}
//			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
//				throw e.setUnfinishedMessage(this);
//			} catch (java.io.IOException e) {
//				throw new com.google.protobuf.InvalidProtocolBufferException(
//						e.getMessage()).setUnfinishedMessage(this);
//			} finally {
//				this.unknownFields = unknownFields.build();
//				makeExtensionsImmutable();
//			}
//		}
//
//		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
//			return QQUserProtos.internal_static_QQUser_descriptor;
//		}
//
//		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
//			return QQUserProtos.internal_static_QQUser_fieldAccessorTable
//					.ensureFieldAccessorsInitialized(
//							QQUserProtos.QQUser.class,
//							QQUserProtos.QQUser.Builder.class);
//		}
//
//		public static com.google.protobuf.Parser<QQUser> PARSER = new com.google.protobuf.AbstractParser<QQUser>() {
//			public QQUser parsePartialFrom(
//					com.google.protobuf.CodedInputStream input,
//					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//					throws com.google.protobuf.InvalidProtocolBufferException {
//				return new QQUser(input, extensionRegistry);
//			}
//		};
//
//		@java.lang.Override
//		public com.google.protobuf.Parser<QQUser> getParserForType() {
//			return PARSER;
//		}
//
//		private int bitField0_;
//		// required int32 uin = 1 [default = 10000];
//		public static final int UIN_FIELD_NUMBER = 1;
//		private int uin_;
//
//		/**
//		 * <code>required int32 uin = 1 [default = 10000];</code>
//		 */
//		public boolean hasUin() {
//			return ((bitField0_ & 0x00000001) == 0x00000001);
//		}
//
//		/**
//		 * <code>required int32 uin = 1 [default = 10000];</code>
//		 */
//		public int getUin() {
//			return uin_;
//		}
//
//		// required string nick = 2 [default = "n"];
//		public static final int NICK_FIELD_NUMBER = 2;
//		private java.lang.Object nick_;
//
//		/**
//		 * <code>required string nick = 2 [default = "n"];</code>
//		 */
//		public boolean hasNick() {
//			return ((bitField0_ & 0x00000002) == 0x00000002);
//		}
//
//		/**
//		 * <code>required string nick = 2 [default = "n"];</code>
//		 */
//		public java.lang.String getNick() {
//			java.lang.Object ref = nick_;
//			if (ref instanceof java.lang.String) {
//				return (java.lang.String) ref;
//			} else {
//				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
//				java.lang.String s = bs.toStringUtf8();
//				if (bs.isValidUtf8()) {
//					nick_ = s;
//				}
//				return s;
//			}
//		}
//
//		/**
//		 * <code>required string nick = 2 [default = "n"];</code>
//		 */
//		public com.google.protobuf.ByteString getNickBytes() {
//			java.lang.Object ref = nick_;
//			if (ref instanceof java.lang.String) {
//				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
//						.copyFromUtf8((java.lang.String) ref);
//				nick_ = b;
//				return b;
//			} else {
//				return (com.google.protobuf.ByteString) ref;
//			}
//		}
//
//		// required int32 age = 3 [default = 20];
//		public static final int AGE_FIELD_NUMBER = 3;
//		private int age_;
//
//		/**
//		 * <code>required int32 age = 3 [default = 20];</code>
//		 */
//		public boolean hasAge() {
//			return ((bitField0_ & 0x00000004) == 0x00000004);
//		}
//
//		/**
//		 * <code>required int32 age = 3 [default = 20];</code>
//		 */
//		public int getAge() {
//			return age_;
//		}
//
//		// required int32 faceId = 4 [default = 0];
//		public static final int FACEID_FIELD_NUMBER = 4;
//		private int faceId_;
//
//		/**
//		 * <code>required int32 faceId = 4 [default = 0];</code>
//		 */
//		public boolean hasFaceId() {
//			return ((bitField0_ & 0x00000008) == 0x00000008);
//		}
//
//		/**
//		 * <code>required int32 faceId = 4 [default = 0];</code>
//		 */
//		public int getFaceId() {
//			return faceId_;
//		}
//
//		private void initFields() {
//			uin_ = 10000;
//			nick_ = "n";
//			age_ = 20;
//			faceId_ = 0;
//		}
//
//		private byte memoizedIsInitialized = -1;
//
//		public final boolean isInitialized() {
//			byte isInitialized = memoizedIsInitialized;
//			if (isInitialized != -1)
//				return isInitialized == 1;
//
//			if (!hasUin()) {
//				memoizedIsInitialized = 0;
//				return false;
//			}
//			if (!hasNick()) {
//				memoizedIsInitialized = 0;
//				return false;
//			}
//			if (!hasAge()) {
//				memoizedIsInitialized = 0;
//				return false;
//			}
//			if (!hasFaceId()) {
//				memoizedIsInitialized = 0;
//				return false;
//			}
//			memoizedIsInitialized = 1;
//			return true;
//		}
//
//		public void writeTo(com.google.protobuf.CodedOutputStream output)
//				throws java.io.IOException {
//			getSerializedSize();
//			if (((bitField0_ & 0x00000001) == 0x00000001)) {
//				output.writeInt32(1, uin_);
//			}
//			if (((bitField0_ & 0x00000002) == 0x00000002)) {
//				output.writeBytes(2, getNickBytes());
//			}
//			if (((bitField0_ & 0x00000004) == 0x00000004)) {
//				output.writeInt32(3, age_);
//			}
//			if (((bitField0_ & 0x00000008) == 0x00000008)) {
//				output.writeInt32(4, faceId_);
//			}
//			getUnknownFields().writeTo(output);
//		}
//
//		private int memoizedSerializedSize = -1;
//
//		public int getSerializedSize() {
//			int size = memoizedSerializedSize;
//			if (size != -1)
//				return size;
//
//			size = 0;
//			if (((bitField0_ & 0x00000001) == 0x00000001)) {
//				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
//						1, uin_);
//			}
//			if (((bitField0_ & 0x00000002) == 0x00000002)) {
//				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
//						2, getNickBytes());
//			}
//			if (((bitField0_ & 0x00000004) == 0x00000004)) {
//				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
//						3, age_);
//			}
//			if (((bitField0_ & 0x00000008) == 0x00000008)) {
//				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
//						4, faceId_);
//			}
//			size += getUnknownFields().getSerializedSize();
//			memoizedSerializedSize = size;
//			return size;
//		}
//
//		private static final long serialVersionUID = 0L;
//
//		@java.lang.Override
//		protected java.lang.Object writeReplace()
//				throws java.io.ObjectStreamException {
//			return super.writeReplace();
//		}
//
//		public static QQUserProtos.QQUser parseFrom(
//				com.google.protobuf.ByteString data)
//				throws com.google.protobuf.InvalidProtocolBufferException {
//			return PARSER.parseFrom(data);
//		}
//
//		public static QQUserProtos.QQUser parseFrom(
//				com.google.protobuf.ByteString data,
//				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//				throws com.google.protobuf.InvalidProtocolBufferException {
//			return PARSER.parseFrom(data, extensionRegistry);
//		}
//
//		public static QQUserProtos.QQUser parseFrom(
//				byte[] data)
//				throws com.google.protobuf.InvalidProtocolBufferException {
//			return PARSER.parseFrom(data);
//		}
//
//		public static QQUserProtos.QQUser parseFrom(
//				byte[] data,
//				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//				throws com.google.protobuf.InvalidProtocolBufferException {
//			return PARSER.parseFrom(data, extensionRegistry);
//		}
//
//		public static QQUserProtos.QQUser parseFrom(
//				java.io.InputStream input) throws java.io.IOException {
//			return PARSER.parseFrom(input);
//		}
//
//		public static QQUserProtos.QQUser parseFrom(
//				java.io.InputStream input,
//				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//				throws java.io.IOException {
//			return PARSER.parseFrom(input, extensionRegistry);
//		}
//
//		public static QQUserProtos.QQUser parseDelimitedFrom(
//				java.io.InputStream input) throws java.io.IOException {
//			return PARSER.parseDelimitedFrom(input);
//		}
//
//		public static QQUserProtos.QQUser parseDelimitedFrom(
//				java.io.InputStream input,
//				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//				throws java.io.IOException {
//			return PARSER.parseDelimitedFrom(input, extensionRegistry);
//		}
//
//		public static QQUserProtos.QQUser parseFrom(
//				com.google.protobuf.CodedInputStream input)
//				throws java.io.IOException {
//			return PARSER.parseFrom(input);
//		}
//
//		public static QQUserProtos.QQUser parseFrom(
//				com.google.protobuf.CodedInputStream input,
//				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//				throws java.io.IOException {
//			return PARSER.parseFrom(input, extensionRegistry);
//		}
//
//		public static Builder newBuilder() {
//			return Builder.create();
//		}
//
//		public Builder newBuilderForType() {
//			return newBuilder();
//		}
//
//		public static Builder newBuilder(
//				QQUserProtos.QQUser prototype) {
//			return newBuilder().mergeFrom(prototype);
//		}
//
//		public Builder toBuilder() {
//			return newBuilder(this);
//		}
//
//		@java.lang.Override
//		protected Builder newBuilderForType(
//				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//			Builder builder = new Builder(parent);
//			return builder;
//		}
//
//		/**
//		 * Protobuf type {@code QQUser}
//		 */
//		public static final class Builder extends
//				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
//				QQUserProtos.QQUserOrBuilder {
//			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
//				return QQUserProtos.internal_static_QQUser_descriptor;
//			}
//
//			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
//				return QQUserProtos.internal_static_QQUser_fieldAccessorTable
//						.ensureFieldAccessorsInitialized(
//								QQUserProtos.QQUser.class,
//								QQUserProtos.QQUser.Builder.class);
//			}
//
//			// Construct using
//			// osc.innovator.arbitrarygen.demo.QQUserProtos.QQUser.newBuilder()
//			private Builder() {
//				maybeForceBuilderInitialization();
//			}
//
//			private Builder(
//					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
//				super(parent);
//				maybeForceBuilderInitialization();
//			}
//
//			private void maybeForceBuilderInitialization() {
//				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
//				}
//			}
//
//			private static Builder create() {
//				return new Builder();
//			}
//
//			public Builder clear() {
//				super.clear();
//				uin_ = 10000;
//				bitField0_ = (bitField0_ & ~0x00000001);
//				nick_ = "n";
//				bitField0_ = (bitField0_ & ~0x00000002);
//				age_ = 20;
//				bitField0_ = (bitField0_ & ~0x00000004);
//				faceId_ = 0;
//				bitField0_ = (bitField0_ & ~0x00000008);
//				return this;
//			}
//
//			public Builder clone() {
//				return create().mergeFrom(buildPartial());
//			}
//
//			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
//				return QQUserProtos.internal_static_QQUser_descriptor;
//			}
//
//			public QQUserProtos.QQUser getDefaultInstanceForType() {
//				return QQUserProtos.QQUser
//						.getDefaultInstance();
//			}
//
//			public QQUserProtos.QQUser build() {
//				QQUserProtos.QQUser result = buildPartial();
//				if (!result.isInitialized()) {
//					throw newUninitializedMessageException(result);
//				}
//				return result;
//			}
//
//			public QQUserProtos.QQUser buildPartial() {
//				QQUserProtos.QQUser result = new QQUserProtos.QQUser(
//						this);
//				int from_bitField0_ = bitField0_;
//				int to_bitField0_ = 0;
//				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
//					to_bitField0_ |= 0x00000001;
//				}
//				result.uin_ = uin_;
//				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
//					to_bitField0_ |= 0x00000002;
//				}
//				result.nick_ = nick_;
//				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
//					to_bitField0_ |= 0x00000004;
//				}
//				result.age_ = age_;
//				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
//					to_bitField0_ |= 0x00000008;
//				}
//				result.faceId_ = faceId_;
//				result.bitField0_ = to_bitField0_;
//				onBuilt();
//				return result;
//			}
//
//			public Builder mergeFrom(com.google.protobuf.Message other) {
//				if (other instanceof QQUserProtos.QQUser) {
//					return mergeFrom((QQUserProtos.QQUser) other);
//				} else {
//					super.mergeFrom(other);
//					return this;
//				}
//			}
//
//			public Builder mergeFrom(
//					QQUserProtos.QQUser other) {
//				if (other == QQUserProtos.QQUser
//						.getDefaultInstance())
//					return this;
//				if (other.hasUin()) {
//					setUin(other.getUin());
//				}
//				if (other.hasNick()) {
//					bitField0_ |= 0x00000002;
//					nick_ = other.nick_;
//					onChanged();
//				}
//				if (other.hasAge()) {
//					setAge(other.getAge());
//				}
//				if (other.hasFaceId()) {
//					setFaceId(other.getFaceId());
//				}
//				this.mergeUnknownFields(other.getUnknownFields());
//				return this;
//			}
//
//			public final boolean isInitialized() {
//				if (!hasUin()) {
//
//					return false;
//				}
//				if (!hasNick()) {
//
//					return false;
//				}
//				if (!hasAge()) {
//
//					return false;
//				}
//				if (!hasFaceId()) {
//
//					return false;
//				}
//				return true;
//			}
//
//			public Builder mergeFrom(
//					com.google.protobuf.CodedInputStream input,
//					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//					throws java.io.IOException {
//				QQUserProtos.QQUser parsedMessage = null;
//				try {
//					parsedMessage = PARSER.parsePartialFrom(input,
//							extensionRegistry);
//				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
//					parsedMessage = (QQUserProtos.QQUser) e
//							.getUnfinishedMessage();
//					throw e;
//				} finally {
//					if (parsedMessage != null) {
//						mergeFrom(parsedMessage);
//					}
//				}
//				return this;
//			}
//
//			private int bitField0_;
//
//			// required int32 uin = 1 [default = 10000];
//			private int uin_ = 10000;
//
//			/**
//			 * <code>required int32 uin = 1 [default = 10000];</code>
//			 */
//			public boolean hasUin() {
//				return ((bitField0_ & 0x00000001) == 0x00000001);
//			}
//
//			/**
//			 * <code>required int32 uin = 1 [default = 10000];</code>
//			 */
//			public int getUin() {
//				return uin_;
//			}
//
//			/**
//			 * <code>required int32 uin = 1 [default = 10000];</code>
//			 */
//			public Builder setUin(int value) {
//				bitField0_ |= 0x00000001;
//				uin_ = value;
//				onChanged();
//				return this;
//			}
//
//			/**
//			 * <code>required int32 uin = 1 [default = 10000];</code>
//			 */
//			public Builder clearUin() {
//				bitField0_ = (bitField0_ & ~0x00000001);
//				uin_ = 10000;
//				onChanged();
//				return this;
//			}
//
//			// required string nick = 2 [default = "n"];
//			private java.lang.Object nick_ = "n";
//
//			/**
//			 * <code>required string nick = 2 [default = "n"];</code>
//			 */
//			public boolean hasNick() {
//				return ((bitField0_ & 0x00000002) == 0x00000002);
//			}
//
//			/**
//			 * <code>required string nick = 2 [default = "n"];</code>
//			 */
//			public java.lang.String getNick() {
//				java.lang.Object ref = nick_;
//				if (!(ref instanceof java.lang.String)) {
//					java.lang.String s = ((com.google.protobuf.ByteString) ref)
//							.toStringUtf8();
//					nick_ = s;
//					return s;
//				} else {
//					return (java.lang.String) ref;
//				}
//			}
//
//			/**
//			 * <code>required string nick = 2 [default = "n"];</code>
//			 */
//			public com.google.protobuf.ByteString getNickBytes() {
//				java.lang.Object ref = nick_;
//				if (ref instanceof String) {
//					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
//							.copyFromUtf8((java.lang.String) ref);
//					nick_ = b;
//					return b;
//				} else {
//					return (com.google.protobuf.ByteString) ref;
//				}
//			}
//
//			/**
//			 * <code>required string nick = 2 [default = "n"];</code>
//			 */
//			public Builder setNick(java.lang.String value) {
//				if (value == null) {
//					throw new NullPointerException();
//				}
//				bitField0_ |= 0x00000002;
//				nick_ = value;
//				onChanged();
//				return this;
//			}
//
//			/**
//			 * <code>required string nick = 2 [default = "n"];</code>
//			 */
//			public Builder clearNick() {
//				bitField0_ = (bitField0_ & ~0x00000002);
//				nick_ = getDefaultInstance().getNick();
//				onChanged();
//				return this;
//			}
//
//			/**
//			 * <code>required string nick = 2 [default = "n"];</code>
//			 */
//			public Builder setNickBytes(com.google.protobuf.ByteString value) {
//				if (value == null) {
//					throw new NullPointerException();
//				}
//				bitField0_ |= 0x00000002;
//				nick_ = value;
//				onChanged();
//				return this;
//			}
//
//			// required int32 age = 3 [default = 20];
//			private int age_ = 20;
//
//			/**
//			 * <code>required int32 age = 3 [default = 20];</code>
//			 */
//			public boolean hasAge() {
//				return ((bitField0_ & 0x00000004) == 0x00000004);
//			}
//
//			/**
//			 * <code>required int32 age = 3 [default = 20];</code>
//			 */
//			public int getAge() {
//				return age_;
//			}
//
//			/**
//			 * <code>required int32 age = 3 [default = 20];</code>
//			 */
//			public Builder setAge(int value) {
//				bitField0_ |= 0x00000004;
//				age_ = value;
//				onChanged();
//				return this;
//			}
//
//			/**
//			 * <code>required int32 age = 3 [default = 20];</code>
//			 */
//			public Builder clearAge() {
//				bitField0_ = (bitField0_ & ~0x00000004);
//				age_ = 20;
//				onChanged();
//				return this;
//			}
//
//			// required int32 faceId = 4 [default = 0];
//			private int faceId_;
//
//			/**
//			 * <code>required int32 faceId = 4 [default = 0];</code>
//			 */
//			public boolean hasFaceId() {
//				return ((bitField0_ & 0x00000008) == 0x00000008);
//			}
//
//			/**
//			 * <code>required int32 faceId = 4 [default = 0];</code>
//			 */
//			public int getFaceId() {
//				return faceId_;
//			}
//
//			/**
//			 * <code>required int32 faceId = 4 [default = 0];</code>
//			 */
//			public Builder setFaceId(int value) {
//				bitField0_ |= 0x00000008;
//				faceId_ = value;
//				onChanged();
//				return this;
//			}
//
//			/**
//			 * <code>required int32 faceId = 4 [default = 0];</code>
//			 */
//			public Builder clearFaceId() {
//				bitField0_ = (bitField0_ & ~0x00000008);
//				faceId_ = 0;
//				onChanged();
//				return this;
//			}
//			// @@protoc_insertion_point(outer_class_scope)
//		}
//
//		static {
//			defaultInstance = new QQUser(true);
//			defaultInstance.initFields();
//		}
//		// @@protoc_insertion_point(outer_class_scope)
//	}
//
//	private static com.google.protobuf.Descriptors.Descriptor internal_static_QQUser_descriptor;
//	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_QQUser_fieldAccessorTable;
//
//	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
//		return descriptor;
//	}
//
//	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
//	static {
//		java.lang.String[] descriptorData = { "\n\014entity.proto\"Q\n\006QQUser\022\022\n\003uin\030\001 \002(\005:\0051"
//				+ "0000\022\017\n\004nick\030\002 \002(\t:\001n\022\017\n\003age\030\003 \002(\005:\00220\022\021"
//				+ "\n\006faceId\030\004 \002(\005:\0010B\"\n\022com.lizongbo.beansB"
//				+ "\014QQUserProtos" };
//		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
//			public com.google.protobuf.ExtensionRegistry assignDescriptors(
//					com.google.protobuf.Descriptors.FileDescriptor root) {
//				descriptor = root;
//				internal_static_QQUser_descriptor = getDescriptor()
//						.getMessageTypes().get(0);
//				internal_static_QQUser_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
//						internal_static_QQUser_descriptor,
//						new java.lang.String[] { "Uin", "Nick", "Age",
//								"FaceId", });
//				return null;
//			}
//		};
//		com.google.protobuf.Descriptors.FileDescriptor
//				.internalBuildGeneratedFileFrom(
//						descriptorData,
//						new com.google.protobuf.Descriptors.FileDescriptor[] {},
//						assigner);
//	}
//
//	// @@protoc_insertion_point(outer_class_scope)
//}
