package cc.suitalk.player.autogen.table;

import cc.suitalk.sdk.db.base.IDatabaseEngine;
import cc.suitalk.sdk.db.base.IDatabaseInfoDelegate;

/*@@@#SCRIPT-BEGIN#
<%var _tables = _hybrid_tables;%>
<%if (_tables && _tables.length > 0) {%>
	<%for (var i = 0; i < _tables.length; i++) {%>
import <%=_package%>.<%=_tables[i]._name%>;<%}%>
<%}%>
#SCRIPT-END#@@@*/

/**
 * Generated by ScriptCodeGenEngine.
 * <p/>
 * Auto generate add {@link cc.suitalk.sdk.db.VigorDBInfo} into {@link IDatabaseEngine} here.
 *
 * @author AlbieLiang
 */
public class VDBInfoDelegate implements IDatabaseInfoDelegate {

    private static final String TAG = "AutoGen.VDBInfoDelegate";

    @Override
    public void delegate(IDatabaseEngine engine) {
        // Auto generate code here

        /*@@@#SCRIPT-BEGIN#
        <%if (_tables && _tables.length > 0) {%>
           <%for (var i = 0; i < _tables.length; i++) {%>
        engine.addDatabaseInfo(<%=_tables[i]._name%>.getVDBInfo());<%}%>
        <%}%>
        #SCRIPT-END#@@@*/
    }
}





